# Generated by Django 4.1.3 on 2023-11-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture_url',
            field=models.URLField(blank=True, max_length=100000000),
        ),
    ]
