# Generated by Django 4.1.3 on 2023-11-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture_url',
            field=models.URLField(blank=True, editable=False, max_length=100000000),
        ),
    ]
